name: sigma-srn
channels:
  - pytorch
  - defaults
dependencies:
  - configargparse=0.14.0
  - imageio=2.5.0
  - matplotlib=3.1.1
  - pandas=0.25.1
  - pillow=6.1.0
  - pip=19.2.3
  - python=3.7
  - scikit-image=0.15.0
  - torchvision=0.4.0
  - pip:
    - absl-py==0.8.0
    - dask==2.4.0
    - functorch==0.1.1
    - future==0.17.1
    - grpcio==1.23.0
    - ipykernel
    - markdown==3.1.1
    - opencv-python==3.4.2.17
    - piq==0.7.0
    - protobuf==3.9.2
    - pybind11==2.2.4
    - tensorboard==2.0.0
    - torch==1.11.0
    - werkzeug==0.16.0
